### ISSUE TITLE
ブランチは自分の名前で作成してください。

### ISSUE THREAD

**Issue by fujimoto-mio** [fujimoto-mio/techUP_study#8]
gitを自身で行う場合は、自分のブランチを切ってプッシュしてください。
そうしないとマージする時コンフリクトおきやすくなります。
git branch  feature/xxxx  （xxxx 自分の名前ローマ字）

最初のブッシュ
git push origin HEAD　or　git push origin ブランチ名

**Comment by yujiro827** [comment]
git branch feature/matuokayujiro

git push origin Mywebにて再度pushさせていただきました。
